### PR TITLE
feat: generate typescript api

### PR DESCRIPTION
**Pull request by ReuDa**
@bripkens Do you think the generated API is usable?

### CODE REVIEW

**Comment by bripkens** [comment]
To me this looks pretty far away from TypeScript best-practices and idiomatic TypeScript/JavaScript :(. Optional props/enums are nicely declared, but this mapping under `components` is very weird. I'd also expect ESM syntax.

**Comment by ReuDa** [comment]
@bripkens I've added another generator, which generates the API to `/api`. Looks better, but have you any idea why for example, `DescribingEndpoint` has no attributes?

**Comment by bripkens** [comment]
> has no attributes?

nope, sorry, no idea :(

**Comment by ReuDa** [comment]
No satisfying results during the time box. I will close this PR and add a hint to the typescript APIs that we currently don't maintain them.

**Pull request closed without merging**
